* Exercises Section 11.1
** Exercise 11.1
   #+BEGIN_QUOTE
   Describe the differences between a ~map~ and a ~vector~.
   #+END_QUOTE

   Associative (~map~) and sequential (~vector~) containers differ from one
   another in a fundamental way: Elements in an associative container are stored
   and retrieved by a key. In contrast, elements in a sequential container are
   stored and accessed sequentially by their position in the container.

   Although the associative containers share much of the behavior of the
   sequential containers, they differ from the sequential containers in ways
   that reflect the use of keys.

** Exercise 11.2
   #+BEGIN_QUOTE
   Give an example of when each of ~list~, ~vector~, ~deque~, ~map~, and ~set~
   might be most useful.
   #+END_QUOTE

   + ~list~ : When a doubly-linked list is required.
   + ~vector~ : When a dynamic array is required.
   + ~deque~ : When we need "fast access" to insert/deletes at both ends of the
     line.
   + ~map~ : A dictionary would be a good use for a map: The word would be the
     key, and its definition would be the value.
   + ~set~ : We might use a set to hold words that we want to ignore during some
     kind of text processing.

** Exercise 11.3
   #+BEGIN_QUOTE
   Write your own version of the word-counting program.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <cstddef>
using std::size_t;

#include <string>
using std::string;

#include <map>
using std::map;

int main()
{
  // count the number of times each word occurs in the input
  map<string, size_t> word_count; // empty map from string to size_t
  string word;
  while (cin >> word)
    ++word_count[word];		// fetch and increment the counter for word
  for (const auto &w : word_count) // for each element in the map
    // print the results
    cout << w.first << " occurs " << w.second
	 << ((w.second > 1) ? " times" : " time") << endl;

  return 0;
}
   #+END_SRC

** Exercise 11.4
   #+BEGIN_QUOTE
   Extend your program to ignore case and punctuation. For example, “example.”
   “example,” and “Example” should all increment the same counter.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <cstddef>
using std::size_t;

#include <cctype>
using std::tolower; using std::ispunct;

#include <string>
using std::string;

#include <map>
using std::map;

#include <algorithm>
using std::for_each; using std::remove_if;

int main()
{
  // count the number of times each word occurs in the input
  map<string, size_t> word_count; // empty map from string to size_t
  string word;
  while (cin >> word) {
    for_each(word.begin(), word.end(), [](char &c) { tolower(c); });
    auto iter = remove_if(word.begin(), word.end(),
			  [](char c)
			  { return ispunct(static_cast<unsigned char>(c)); });
    word.erase(iter, word.end());
    ++word_count[word];		// fetch and increment the counter for word
  }

  for (const auto &w : word_count) // for each element in the map
    // print the results
    cout << w.first << " occurs " << w.second
	 << ((w.second > 1) ? " times" : " time") << endl;

  return 0;
}
   #+END_SRC

* Exercises Section 11.2.1
** Exercise 11.5
   #+BEGIN_QUOTE
   Explain the difference between a ~map~ and a ~set~. When might you use one or
   the other?
   #+END_QUOTE

   Both ~std::set~ and ~std::map~ are associative containers. The difference is
   that ~std::sets~ contain only the key, while in ~std::map~ there is an
   associated value. Choosing one over the other depends mainly on what the task
   at hand is. If you want to build a dictionary of all the words that appear in
   a text, you could use a ~std::set<std::string>~, but if you also want to
   count how many times each word appeared (i.e. associate a value to the key)
   then you would need an ~std::map<std::string,int>~. If you don't need to
   associate that count, it does not make sense to have the ~int~ that is
   unnecessary.

** Exercise 11.6
   #+BEGIN_QUOTE
   Explain the difference between a ~set~ and a ~list~. When might you use one
   or the other?
   #+END_QUOTE

   ~list~:
   + Searching (linear time).
   + Inserting, deleting, moving (takes constant time).
   + Elements may be ordered.
   + Elements may be sorted.
   + Elements may be duplicate.

   ~set~:
   + Searching (logarithmic in size).
   + Insert and delete (logarithimic in general).
   + Elements are un-ordered.
   + Elements are always sorted from lower to higher.
   + Elements are unique.

** Exercise 11.7
   #+BEGIN_QUOTE
   Define a ~map~ for which the key is the family’s last name and the value is a
   ~vector~ of the children’s names. Write code to add new families and to add
   new children to an existing family.
   #+END_QUOTE

   Note: each time the program will read a line which represents a single
   person with his/her last_name and first_name.

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include<sstream>
using std::istringstream;

#include <cstddef>
using std::size_t;

#include <vector>
using std::vector;

#include <string>
using std::string;

#include <map>
using std::map;

int main()
{
  map<string, vector<string>> families;
  string line;
  while (getline(cin, line)) {
    istringstream str(line);
    string last_name, first_name;
    str >> last_name >> first_name;
    families[last_name].push_back(first_name);
  }

  for (const auto &m : families) {
    cout << "Family: " << m.first << endl
	 << "Children: ";
    for (const auto &v : m.second) {
      cout << v << " ";
    }
    cout << endl;
  }

  return 0;
}
   #+END_SRC

** Exercise 11.8
   #+BEGIN_QUOTE
   Write a program that stores the excluded words in a ~vector~ instead of in a
   ~set~. What are the advantages to using a ~set~?
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <string>
using std::string;

#include <vector>
using std::vector;

#include <map>
using std::map;

#include <algorithm>
using std::find;

int main()
{
    vector<string> exclude = {"the", "but", "and", "or", "an", "a",
			      "The", "But", "And", "Or", "An", "A"};
    map<string, size_t> word_count; // empty map from string to size_t
    string word;
    while (cin >> word) {
      if (find(exclude.begin(), exclude.end(), word) == exclude.end()) {
	++word_count[word];
      } else {
	cout << "excluded: " << word << endl;
      }
    }
    for (const auto &w : word_count) // for each element in the map
      // print the results
      cout << w.first << " occurs " << w.second
	   << ((w.second > 1) ? " times" : " time") << endl;

    return 0;
}
   #+END_SRC

   A ~set~ is ordered. It is guaranteed to remain in a specific ordering,
   according to a functor that you provide. No matter what elements you add or
   remove (unless you add a duplicate, which is not allowed in a ~set~), it will
   always be ordered.

   A ~vector~ has exactly and only the ordering you explicitly give it. Items in
   a ~vector~ are where you put them. If you put them in out of order, then
   they're out of order; you now need to sort the container to put them back in
   order.

   Admittedly, ~set~ has relatively limited use. With proper discipline, one
   could insert items into a ~vector~ and keep it ordered. However, if you are
   constantly inserting and removing items from the container, vector will run
   into many issues. It will be doing a lot of copying/moving of elements and so
   forth, since it is effectively just an array.

   The time it takes to insert an item into a ~vector~ is proportional to the
   number of items already in the ~vector~. The time it takes to insert an item
   into a ~set~ is proportional to the log2 of the number of items. If the
   number of items is large, that's a huge difference. log2(100,000) is ~16;
   that's a major speed improvement. The same goes for removal.

   However, if you do all of your insertions at once, at initialization time,
   then there's no problem. You can insert everything into the ~vector~, sort it
   (paying that price once), and then use standard algorithms for sorted vectors
   to find elements and iterate over the sorted list. And while iteration over
   the elements of a ~set~ isn't exactly slow, iterating over a ~vector~ is
   faster.

   So there are cases where a sorted ~vector~ beats a ~set~. That being said,
   you really shouldn't bother with the expense of this kind of optimization
   unless you know that it is necessary. So use a ~set~ unless you have
   experience with the kind of system you're writing (and thus know that you
   need that performance) or have profiling data in hand that tells you that you
   need a ~vector~ and not a ~set~.

* Exercises Section 11.2.2
** Exercise 11.9
   #+BEGIN_QUOTE
   Define a ~map~ that associates words with a ~list~ of line numbers on which
   the word might occur.
   #+END_QUOTE

   ~std::map<std::string, std::vector<std::size_t>> m;~

** Exercise 11.10
   #+BEGIN_QUOTE
   Could we define a ~map~ from ~vector<int>::iterator~ to ~int~? What about
   from ~list<int>::iterator~ to ~int~? In each case, if not, why not?
   #+END_QUOTE

   we can define a ~map~ from ~vector<int>::iterator~ to ~int~; we cannot define
   a ~map~ from ~list<int>::iterator~ to ~int~ since ~<~ opratator is not
   defined for the ~list<int>::iterator~ to compare the keys.

** Exercise 11.11
   #+BEGIN_QUOTE
   Redefine bookstore without using decltype.
   #+END_QUOTE

   #+BEGIN_SRC C++
bool (*pf)(const Sales_data &lhs, const Sales_data &rhs);
multiset<Sales_data, pf> bookstore(compareIsbn);
   #+END_SRC

* Exercises Section 11.2.3
** Exercise 11.12
   #+BEGIN_QUOTE
   Write a program to read a sequence of ~string~ s and ~int~ s, storing each
   into a ~pair~. Store the ~pair~ s in a ~vector~.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <string>
using std::string;

#include <vector>
using std::vector;

#include <utility>
using std::pair;

int main()
{
  vector<pair<string, int>> vec;

  string str;
  int ival;
  while (cin >> str >> ival) {
    vec.push_back({str, ival});
  }

  for (const auto &p : vec) {
    cout << p.first << " " << p.second << endl;
  }

  return 0;
}
   #+END_SRC

** Exercise 11.13
   #+BEGIN_QUOTE
   There are at least three ways to create the ~pair~ s in the program for the
   previous exercise. Write three versions of that program, creating the ~pair~ s
   in each way. Explain which form you think is easiest to write and understand,
   and why.
   #+END_QUOTE

   #+BEGIN_SRC C++
vec.push_back({str, ival});          // easiest to write and understand
vec.push_back(pair<string, int>(str, ival));
vec.push_back(make_pair(str, ival));
   #+END_SRC

** Exercise 11.14
   #+BEGIN_QUOTE
   Extend the ~map~ of children to their family name that you wrote for the
   exercises in § 11.2.1 (p. 424) by having the ~vector~ store a ~pair~ that
   holds a child’s name and birthday.
   #+END_QUOTE

   Note: each time the program will read a line which represents a single person
   with his/her last_name, first_name and birthday.
   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include<sstream>
using std::istringstream;

#include <cstddef>
using std::size_t;

#include <vector>
using std::vector;

#include <string>
using std::string;

#include <map>
using std::map;

#include <utility>
using std::pair;

int main()
{
  map<string, vector<pair<string, string>>> families;
  string line;
  while (getline(cin, line)) {
    istringstream str(line);
    string last_name, first_name, birthday;
    str >> last_name >> first_name >> birthday;
    families[last_name].push_back({first_name, birthday});
  }

  for (const auto &m : families) {
    cout << "Family: " << m.first << endl;
    for (const auto &v : m.second) {
      cout << "Name: " << v.first << " "
	   << "Birthday: " << v.second << endl;
    }
    cout << endl;
  }

  return 0;
}
   #+END_SRC

* Exercises Section 11.3.1
** Exercise 11.15
   #+BEGIN_QUOTE
   What are the ~mapped_type~, ~key_type~, and ~value_type~ of a ~map~ from
   ~int~ to ~vector<int>~?
   #+END_QUOTE

   For ~map<int, vector<int>>~, the ~key_type~ is ~int~, ~mapped_type~ is
   ~vector<int>~ and ~value_type~ is ~pair<const int, vector<int>>~.

** Exercise 11.16
   #+BEGIN_QUOTE
   Using a ~map~ iterator write an expression that assigns a value to an
   element.
   #+END_QUOTE

   #+BEGIN_SRC C++
pair<string, size_t> word_count = {"hello", 5};
auto map_it = word_count.begin();
++map_it->second;
   #+END_SRC

** Exercise 11.17
   #+BEGIN_QUOTE
   Assuming ~c~ is a ~multiset~ of ~string~ s and ~v~ is a ~vector~ of ~string~
   s, explain the following calls. Indicate whether each call is legal:
   #+END_QUOTE
   #+BEGIN_SRC C++
copy(v.begin(), v.end(), inserter(c, c.end()));
copy(v.begin(), v.end(), back_inserter(c));
copy(c.begin(), c.end(), inserter(v, v.end()));
copy(c.begin(), c.end(), back_inserter(v));
   #+END_SRC

   + ~copy(v.begin(), v.end(), inserter(c, c.end()));~ will copy all elements in
     ~v~ to the end of ~c~;
   + ~copy(v.begin(), v.end(), back_inserter(c));~ is illegal. ~push_back~ is
     not definied in ~set~;
   + both ~copy(c.begin(), c.end(), inserter(v, v.end()));~ and ~copy(c.begin(),
     c.end(), back_inserter(v));~ will copy all elements in ~c~ to the end of
     ~v~.

** Exercise 11.18
   #+BEGIN_QUOTE
   Write the type of ~map_it~ from the loop on page 430 without using ~auto~ or
   ~decltype~.
   #+END_QUOTE

   ~pair<string, size_t>::const_iterator~

** Exercise 11.19
   #+BEGIN_QUOTE
   Define a variable that you initialize by calling ~begin()~ on the ~multiset~
   named ~bookstore~ from § 11.2.2 (p. 425). Write the variable’s type without
   using ~auto~ or ~decltype~.
   #+END_QUOTE

   #+BEGIN_SRC C++
bool (*pf)(const Sales_data &lhs, const Sales_data &rhs);
multiset<Sales_data, pf> bookstore(compareIsbn);
multiset<Sales_data, pf>::iterator mset_it = bookstore.begin();
   #+END_SRC

* Exercises Section 11.3.2
**  Exercise 11.20
   #+BEGIN_QUOTE
   Rewrite the word-counting program from § 11.1 (p. 421) to use ~insert~
   instead of subscripting. Which program do you think is easier to write and
   read? Explain your reasoning.
   #+END_QUOTE

   Obviously the one use subscripting is easier to write and read.
   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <cstddef>
using std::size_t;

#include <string>
using std::string;

#include <map>
using std::map;

int main()
{
  // count the number of times each word occurs in the input
  map<string, size_t> word_count; // empty map from string to size_t
  string word;
  while (cin >> word) {
    auto ret = word_count.insert({word, 1});
    if (!ret.second) ++ret.first->second;
  }
  for (const auto &w : word_count) // for each element in the map
    // print the results
    cout << w.first << " occurs " << w.second
         << ((w.second > 1) ? " times" : " time") << endl;

  return 0;
}
   #+END_SRC

** Exercise 11.21
   #+BEGIN_QUOTE
   Assuming ~word_count~ is a ~map~ from ~string~ to ~size_t~ and ~word~ is a
   ~string~, explain the following loop:
   #+END_QUOTE

   #+BEGIN_SRC C++
while (cin >> word)
++word_count.insert({word, 0}).first->second;
   #+END_SRC

   The increment statements fetches the iterator, which is the first member of a
   ~pair~ returned from the ~insert~ operation, for the element with the key
   ~word~ and increments the counter associated with the key we tried to insert.

** Exercise 11.22
   #+BEGIN_QUOTE
   Given a ~map<string, vector<int>>~, write the types used as an argument and
   as the return value for the version of ~insert~ that inserts one element.
   #+END_QUOTE

   + used as an argument: ~map<string, vector<int>>::value_type~;
   + used as a return value: ~pair<map<string, vector<int>>::iterator, bool>~.

** Exercise 11.23
   #+BEGIN_QUOTE
   Rewrite the ~map~ that stored ~vector~ s of children’s names with a key that
   is the family last name for the exercises in § 11.2.1 (p. 424) to use a
   ~multimap~.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include<sstream>
using std::istringstream;

#include <cstddef>
using std::size_t;

#include <vector>
using std::vector;

#include <string>
using std::string;

#include <map>
using std::multimap;

int main()
{
  multimap<string, string> families;
  string line;
  while (getline(cin, line)) {
    istringstream str(line);
    string last_name, first_name;
    str >> last_name >> first_name;
    families.insert({last_name, first_name});
  }

  for (const auto &m : families) {
    cout << "Family: " << m.first << endl
         << "Children: " << m.second << endl;
  }

  return 0;
}
   #+END_SRC

* Exercises Section 11.3.4
** Exercise 11.24
   #+BEGIN_QUOTE
   What does the following program do?
   #+END_QUOTE
   #+BEGIN_SRC C++
map<int, int> m;
m[0] = 1;
   #+END_SRC

   + ~m~ is searched for the element whose key is ~0~. The element is not found.
   + A new key-value pair is inserted into ~m~. The key is a ~const int~ holding
     ~0~. The value is value initialized, meaning in this case that the value is
     ~0~.
   + The newly inserted element is fetched and is given the value 1.

** Exercise 11.25
   #+BEGIN_QUOTE
   Contrast the following program with the one in the previous exercise
   #+END_QUOTE
   #+BEGIN_SRC C++
vector<int> v;
v[0] = 1;
   #+END_SRC

   Undefined behaviour (UB) since it's trying to dereference an empty ~vector~.

** Exercise 11.26
   #+BEGIN_QUOTE
   What type can be used to subscript a map? What type does the subscript
   operator return? Give a concrete example—that is, define a map and then write
   the types that can be used to subscript the map and the type that would be
   returned from the subscript operator.
   #+END_QUOTE
   #+BEGIN_SRC C++
set<int> iset = {0,1,2,3,4,5,6,7,8,9};
iset.find(1); // returns an iterator that refers to the element with key == 1
iset.find(11); // returns the iterator == iset.end()
iset.count(1); // returns 1
iset.count(11); // returns 0
   #+END_SRC
