#+STARTUP: content

* Exercises Section 5.1
** Exercise 5.1 
   #+BEGIN_QUOTE
   What is a null statement? When might you use a null statement?
   #+END_QUOTE
   
   A null statement is a single semicolon:
   #+BEGIN_SRC C++
; // null statement   
   #+END_SRC

   A null statement is useful where the language requires a statement but the
   program’s logic does not. Such usage is most common when a loop’s work can be
   done within its condition.

** Exercise 5.2
   #+BEGIN_QUOTE
   What is a block? When might you might use a block?
   #+END_QUOTE
    
   A compound statement, usually referred to as a block, is a (possibly empty)
   sequence of statements and declarations surrounded by a pair of curly
   braces. A block is a scope (§ 2.2.4, p. 48). Names introduced inside a block
   are accessible only in that block and in blocks nested inside that
   block. Names are visible from where they are defined until the end of the
   (immediately) enclosing block. Compound statements are used when the language
   requires a single statement but the logic of our program needs more than one.

** Exercise 5.3
   #+BEGIN_QUOTE
   Use the comma operator (§ 4.10, p. 157) to rewrite the while loop from §
   1.4.1 (p. 11) so that it no longer requires a block. Explain whether this
   rewrite improves or diminishes the readability of this code.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>

int main()
{
  int sum = 0, val = 1;
  // keep executing the while as long as val is less than or equal to 10
  while (val <= 10) 
    sum += val, ++val;
  std::cout << "Sum of 1 to 10 inclusive is "
            << sum << std::endl;

  return 0;
}   
   #+END_SRC

   This rewrite diminishes the readability of this code.

* Exercises Section 5.2
** Exercise 5.4
   #+BEGIN_QUOTE
   Exercise 5.4: Explain each of the following examples, and correct any
   problems you detect.
   + (a) ~while (string::iterator iter != s.end()) { /* . . . */ }~ 
   + (b) ~while (bool status = find(word)) { /*. . . */ } if (!status)
     { /* . . . */ }~
   #+END_QUOTE

   + (a) illegal definition.
     #+BEGIN_SRC C++
string::iterator iter = s.begin();
while (iter != s.end()) { /* . . . */ }     
     #+END_SRC
   + (b) ~status~ is not accessible outside the loop.
     #+BEGIN_SRC C++
bool status; 
while (status = find(word)) { /*. . . */ } if (!status)    
     #+END_SRC

* Exercises Section 5.3.1
** Exercise 5.5
   #+BEGIN_QUOTE
   Using an ~if–else~ statement, write your own version of the program to
   generate the letter grade from a numeric grade.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <string>
using std::string;

#include <vector>
using std::vector;

int main()
{
  // read a set of scores from the input
  vector<unsigned> grades;
  unsigned grade;
  while (cin >> grade)
    grades.push_back(grade);

  const vector<string> scores = {"F", "D", "C", "B", "A", "A++"};
  
  // now process those grades
  for (auto it : grades) {	// for each grade we read
    cout << it << " ";		// print the grade
    string lettergrade;		// hold corresponding letter grade
    // if failing grade, no need to check for a plus or minus
    if (it < 60)
      lettergrade = scores[0];
    else {
      lettergrade = scores[(it - 50)/10]; // fetch the letter grade
      if (it != 100)			      // add plus or minus only if not
					      // already an A++
	if (it % 10 > 7)
	  lettergrade += '+';	// grades ending in 8 or 9 get a +
	else if (it % 10 < 3)
	  lettergrade += '-';	// grades ending in 0, 1 or 2 get a -
    }
    cout << lettergrade << endl;
  }
    
  return 0;
}   
   #+END_SRC

** Exercise 5.6 
   #+BEGIN_QUOTE
   Rewrite your grading program to use the conditional operator (§ 4.7, p. 151)
   in place of the ~if–else~ statement.
   #+END_QUOTE

   #+BEGIN_SRC C++
#include <iostream>
using std::cin; using std::cout; using std::endl;

#include <string>
using std::string;

#include <vector>
using std::vector;

int main()
{
  // read a set of scores from the input
  vector<unsigned> grades;
  unsigned grade;
  while (cin >> grade)
    grades.push_back(grade);

  const vector<string> scores = {"F", "D", "C", "B", "A", "A++"};
  
  // now process those grades
  for (auto it : grades) {	// for each grade we read
    cout << it << " ";		// print the grade
    string lettergrade;		// hold corresponding letter grade

    lettergrade = it < 60 ? scores[0] : scores[(it - 50)/10];
    lettergrade += (it < 60 || it == 100) ? "" :
      (it % 10 > 7) ? "+" :
      (it % 10 < 3) ? "-" : "";
    
    cout << lettergrade << endl;
  }
    
  return 0;
}   
   #+END_SRC
